spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: auth-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/auth/**

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/products/**

            - id: order-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/orders/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 1
                    key-resolver: "#{@userKeyResolver}"

            - id: inventory-service
              uri: lb://INVENTORY_SERVICE
              predicates:
                - Path=/inventory/**

server:
  port: 8085

jwt:
  secret: "change-this-to-a-very-long-secret-at-least-32-bytes"
  expiration-ms: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
