spring:
  application:
    name : product-service
  datasource:
    url : jdbc:postgresql://localhost:5432/productdb
    username : postgres
    password : storm007
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: "change-this-to-a-very-long-secret-at-least-32-bytes"
  expiration-ms: 86400000

logging:
  level:
    com.example.product_service: INFO
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

  retry:
    instances:
      inventoryService:
        maxAttempts: 3
        waitDuration: 500ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
